/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexDotjsonRouteImport } from './routes/search-index[.]json'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as LangDocsIndexRouteImport } from './routes/$lang/docs/index'
import { Route as LangDocsVersionRouteRouteImport } from './routes/$lang/docs/$version/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LangDocsVersionIndexRouteImport } from './routes/$lang/docs/$version/index'
import { Route as LangDocsVersionSplatRouteImport } from './routes/$lang/docs/$version/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexDotjsonRoute = SearchIndexDotjsonRouteImport.update({
  id: '/search-index.json',
  path: '/search-index.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsIndexRoute = LangDocsIndexRouteImport.update({
  id: '/$lang/docs/',
  path: '/$lang/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsVersionRouteRoute = LangDocsVersionRouteRouteImport.update({
  id: '/$lang/docs/$version',
  path: '/$lang/docs/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsVersionIndexRoute = LangDocsVersionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangDocsVersionRouteRoute,
} as any)
const LangDocsVersionSplatRoute = LangDocsVersionSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LangDocsVersionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/': typeof LangIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$lang/docs/$version': typeof LangDocsVersionRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/docs/': typeof LangDocsIndexRoute
  '/$lang/docs/$version/$': typeof LangDocsVersionSplatRoute
  '/$lang/docs/$version/': typeof LangDocsVersionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang': typeof LangIndexRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/docs': typeof LangDocsIndexRoute
  '/$lang/docs/$version/$': typeof LangDocsVersionSplatRoute
  '/$lang/docs/$version': typeof LangDocsVersionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$lang/': typeof LangIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$lang/docs/$version': typeof LangDocsVersionRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$lang/docs/': typeof LangDocsIndexRoute
  '/$lang/docs/$version/$': typeof LangDocsVersionSplatRoute
  '/$lang/docs/$version/': typeof LangDocsVersionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search-index.json'
    | '/sitemap.xml'
    | '/$lang/'
    | '/docs/'
    | '/$lang/docs/$version'
    | '/api/auth/$'
    | '/$lang/docs/'
    | '/$lang/docs/$version/$'
    | '/$lang/docs/$version/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search-index.json'
    | '/sitemap.xml'
    | '/$lang'
    | '/docs'
    | '/api/auth/$'
    | '/$lang/docs'
    | '/$lang/docs/$version/$'
    | '/$lang/docs/$version'
  id:
    | '__root__'
    | '/'
    | '/search-index.json'
    | '/sitemap.xml'
    | '/$lang/'
    | '/docs/'
    | '/$lang/docs/$version'
    | '/api/auth/$'
    | '/$lang/docs/'
    | '/$lang/docs/$version/$'
    | '/$lang/docs/$version/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchIndexDotjsonRoute: typeof SearchIndexDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LangIndexRoute: typeof LangIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  LangDocsVersionRouteRoute: typeof LangDocsVersionRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  LangDocsIndexRoute: typeof LangDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-index.json': {
      id: '/search-index.json'
      path: '/search-index.json'
      fullPath: '/search-index.json'
      preLoaderRoute: typeof SearchIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/': {
      id: '/$lang/docs/'
      path: '/$lang/docs'
      fullPath: '/$lang/docs/'
      preLoaderRoute: typeof LangDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$version': {
      id: '/$lang/docs/$version'
      path: '/$lang/docs/$version'
      fullPath: '/$lang/docs/$version'
      preLoaderRoute: typeof LangDocsVersionRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$version/': {
      id: '/$lang/docs/$version/'
      path: '/'
      fullPath: '/$lang/docs/$version/'
      preLoaderRoute: typeof LangDocsVersionIndexRouteImport
      parentRoute: typeof LangDocsVersionRouteRoute
    }
    '/$lang/docs/$version/$': {
      id: '/$lang/docs/$version/$'
      path: '/$'
      fullPath: '/$lang/docs/$version/$'
      preLoaderRoute: typeof LangDocsVersionSplatRouteImport
      parentRoute: typeof LangDocsVersionRouteRoute
    }
  }
}

interface LangDocsVersionRouteRouteChildren {
  LangDocsVersionSplatRoute: typeof LangDocsVersionSplatRoute
  LangDocsVersionIndexRoute: typeof LangDocsVersionIndexRoute
}

const LangDocsVersionRouteRouteChildren: LangDocsVersionRouteRouteChildren = {
  LangDocsVersionSplatRoute: LangDocsVersionSplatRoute,
  LangDocsVersionIndexRoute: LangDocsVersionIndexRoute,
}

const LangDocsVersionRouteRouteWithChildren =
  LangDocsVersionRouteRoute._addFileChildren(LangDocsVersionRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchIndexDotjsonRoute: SearchIndexDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LangIndexRoute: LangIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  LangDocsVersionRouteRoute: LangDocsVersionRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LangDocsIndexRoute: LangDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
